version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
        command: 'sudo npm install -g'
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: npm install
        command: 'sudo npm install -g'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
